name: Release to GitHub Marketplace

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Verify action.yml
        run: |
          if [ ! -f "action.yml" ]; then
            echo "::error::action.yml must exist for GitHub Actions to be published"
            exit 1
          fi
          
      - name: Verify release tags match
        run: |
          TAG_VERSION="${{ github.event.release.tag_name }}"
          
          # Verify this is a valid semver tag
          if [[ ! $TAG_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Tag must be a valid semver version (v1.0.0)"
            exit 1
          fi
          
          echo "Release $TAG_VERSION is ready for GitHub Marketplace!"
          
      - name: Create major version tag
        run: |
          TAG_VERSION="${{ github.event.release.tag_name }}"
          MAJOR_VERSION=$(echo $TAG_VERSION | sed 's/v\([0-9]*\)\..*/v\1/')
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git tag -d $MAJOR_VERSION || true
          git push origin :refs/tags/$MAJOR_VERSION || true
          git tag $MAJOR_VERSION
          git push origin $MAJOR_VERSION
          
          echo "Created/updated major version tag: $MAJOR_VERSION" 